### PR TITLE
fix decorator pattern problem with big nestings

### PR DESCRIPTION
**Pull request by MSE1188**
### Please check if the PR fulfills these requirements
- [ ] I made sure that my code builds
- [ ] I merged the master into this branch before pushing
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)
#540

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [ ] No

###  Other information

### CODE REVIEW

**Comment by MSE1188** [comment]
What is really interesting is, that as soon as evaluation of the enumerator in ctor is activated, the behaviour of the tests ```CheckEvaluationOfEnumerators``` and ```CheckEvaluationOfFuncOnLengthCall``` changes. They are failing with
1: Assert.Equal() Failure - Expected: 4 - Actual:   1
2: Assert.Equal() Failure- Expected: 10 - Actual:   0

... which is, looking at the tests, the actual behaviour that I would expect (much more efficient, func execution only when necessary)

**Comment by MSE1188** [comment]
it does not seem that evaluation of enumerators in ctor solves the issue. only if you move evaluation of every value into the ctor you can prevent the stacking of func-calls... but I wouldnt go this way..

**Comment by Meerownymous** [comment]
I think, the problem of filling up the stack is not sovable as long as there is a lambda function passed as member in the constructor. I like the object oriented concept of the IEnumerator - it reveals only what is requested and offers delay options for everything else. It refuses direct indexing access as its duty is to enumerate, not be a memory box.

I think that as long as there are lamdba functions passed into ctors, this cannot be prevented for any object offering decorator style combinations as the final building call on the outer object will always travel down to the center object and when that vector is too long for the stack this will happen. 

However, regarding performance, the choice in this library was to offer "sticky by default" and that comes with the cost of performance. We hit the stack upper bounds with less operations due to this, which sets focus on the problem that when combining enumerations there are caches built that are very much unnecessary as they can be disposed once the final enumeration has been formed.

In the secondary Joined ctors I noticed some which copy the whole iteration, which has unnecessary costs when accessing only a fraction of the result. 

Joined offers some ctors which should result in a live object. These should at least be used in Atoms internal objects like Map (where it wasn't used) and it might need prrof to work although. Libraries built ontop of Atoms might profit from raising awareness of this caching costs and using live objects more often.

One thought about LinQ: These are extension (=static) methods and I would guess therefore they cannot do anything else more fancy than somehow decorate their function input...?

**Comment by Meerownymous** [comment]
I prooved the theory of lambda functions in ctors being the cause of stackoverflow to be false. I could eliminate all lambda functions by refactoring, introducing objects like ArrayEnumerator, SingleEnumerator etc.

The problem persists so I think the problem is only solvable by avoiding nesting objects in general, allowing functions to return in a shallow enough call stack.

The guideline of keeping levels of abstraction  as low as possible contributes to this.

However, the unnecessary copying of lists and usage of unnecessary caches, I would like to address.

At the moment, I cannot submit push requests because the library in its current state (.Net Framework version) is not compiling on Mac with M2.

**Comment by Meerownymous** [comment]
Did some more research leading to proposal [here]{https://github.com/icarus-consulting/Yaapii.Atoms/issues/551}

**Comment by MSE1188** [comment]
fixed in #555

**Pull request closed without merging**
