### PR TITLE
ResourceOf handles special characters

### LINKED ISSUE #256: ResourceOf cannot handle special characters in resource names
### Expected Behavior

Resources located in a folder which name contains '.' can be addressed
Update:
Resources located in a folder which name contains '{' and '}' can be addressed
### Actual Behavior

...

Update:
Symbols '{' and '}' will be converted to '_' in the example `path/{id}/folder`

### PR DESCRIPTION
**Pull request by aveXcaesar**
### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

close #256 

### What is the new behavior?

`ResourceOf()` handles special characters in the resource path now.
The following cases can will be successfully handled:
- Dots: Any '.' will be replaced by "._"
- Folders with a number in the beginning: "8text" will be replaced by "_8text"
- The following symbols can be handled in the resource path: '!', '§', '$', '=', '+', '-', '(', ')', '[', ']', '{', '}', ';', ',', '`', '´', '\''

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

###  Other information

### CODE REVIEW

**Comment by aveXcaesar** [comment]
@Meerownymous 
Changes done

**Comment by aveXcaesar** [comment]
We found a new special case which has to be handled here: symbols '{' and '}'.

**Comment by aveXcaesar** [comment]
@Meerownymous 
I added the functionality to handle a list of symbols which has to be encoded.
Ready to review

**Comment by Meerownymous** [comment]
I think the tests should be reduced to one assembly path, instead of dozens.

**Comment by aveXcaesar** [comment]
@aveXcaesar 
Now we have only one path

**Pull request merged**
