### PR TITLE
Add FailOnException class

### LINKED ISSUE #265: New FailOnException<T>
### Expected Behavior

If the action in the FailOnException class  throws the expectd exception type, a specific new exception.
Otherwise throw the original exception

### PR DESCRIPTION
**Pull request by icaOBU**
### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

closes #265 
### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [ ] No

###  Other information

### CODE REVIEW

**Comment by koeeenig** [comment]
@icaOBU please describe the behavior of the new class in #265

**Comment by icaOBU** [comment]
@koeeenig done

**Comment by Meerownymous** [comment]
@icaOBU I think the name is a bit confusing. Can you please rename it to FailConverts?

**Comment by Meerownymous** [comment]
Closed due to inactivity.

**Pull request closed without merging**
