### PR TITLE
fix: TextOf - Ctor uses encoding now

### LINKED ISSUE #218: TextOf ctor does not use given encoding
### Expected Behavior
The TextOf(IBytes bytes, Encoding encoding) - ctor does not use the given Encoding to encode the bytes

### PR DESCRIPTION
**Pull request by MSE1188**
### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)
Closes #218 

### What is the new behavior?
Ctor of TextOf uses the given Encoding to encode Stream

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

###  Other information

### CODE REVIEW

**Comment by Meerownymous** [comment]
@MSE1188 ping... still working on this?

**Comment by Meerownymous** [comment]
@MSE1188 ping...

**Comment by Meerownymous** [comment]
@MSE1188 Pong...

**Comment by MSE1188** [comment]
Finally… done

**Pull request merged**
